version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app  
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+pymysql://dbms:dbms123@db:3306/flask_app
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://dbms:dbms123@db:3306/flask_app

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: flask_app
      MYSQL_USER: dbms
      MYSQL_PASSWORD: dbms123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
