UPDATE expertise_features SET name = 'Chassis Number Check' WHERE name = 'Şaşi No Kontrol';
UPDATE expertise_features SET name = 'Interior Lighting' WHERE name = 'İç Aydınlatma';
UPDATE expertise_features SET name = 'Rearview Mirror' WHERE name = 'Dikiz Aynası';
UPDATE expertise_features SET name = 'Seat Belt Check' WHERE name = 'Emniyet Kemerleri Kontrol';
UPDATE expertise_features SET name = 'Sun Visor Check' WHERE name = 'Güneşlikler Kontrol';
UPDATE expertise_features SET name = 'Glove Compartment Check' WHERE name = 'Torpito Kontrol';
UPDATE expertise_features SET name = 'Steering Check' WHERE name = 'Direksiyon Kontrol';
UPDATE expertise_features SET name = 'Seat Check' WHERE name = 'Koltuklar Kontrol';
UPDATE expertise_features SET name = 'Headliner Check' WHERE name = 'Tavan Döşeme Kontrol';
UPDATE expertise_features SET name = 'Interior Upholstery Check' WHERE name = 'Araç İçi Döşeme Kontrol';
UPDATE expertise_features SET name = 'Window Control Check' WHERE name = 'Cam Kumandası Kontrol';
UPDATE expertise_features SET name = 'Air Conditioning Check' WHERE name = 'Klima Kontrol';
UPDATE expertise_features SET name = 'Instrument Panel Check' WHERE name = 'Gösterge Paneli Kontrol';
UPDATE expertise_features SET name = 'Radio/Tape/Navigation Check' WHERE name = 'Radyo, Teyp, Navigasyon Kontrol';
UPDATE expertise_features SET name = 'Horn' WHERE name = 'Korna';
UPDATE expertise_features SET name = 'Front Headlights' WHERE name = 'Ön Farlar';
UPDATE expertise_features SET name = 'Headlight Washer' WHERE name = 'Far Yıkama';
UPDATE expertise_features SET name = 'Front & Rear Fog Lights' WHERE name = 'Ön - Arka Sisler';
UPDATE expertise_features SET name = 'Turn Signals & Hazard Lights' WHERE name = 'Sinyaller ve Dörtlü İkaz';
UPDATE expertise_features SET name = 'Wipers' WHERE name = 'Silecekler';
UPDATE expertise_features SET name = 'Mirrors' WHERE name = 'Aynalar';
UPDATE expertise_features SET name = 'Sunroof or Glass Roof' WHERE name = 'Sunroof veya Cam Tavan';
UPDATE expertise_features SET name = 'Windows' WHERE name = 'Camlar';
UPDATE expertise_features SET name = 'Door Handles' WHERE name = 'Kapı Kolları';
UPDATE expertise_features SET name = 'Rear Taillights' WHERE name = 'Arka Stoplar';
UPDATE expertise_features SET name = 'License Plate Lighting' WHERE name = 'Plaka Aydınlatma';
UPDATE expertise_features SET name = 'Trunk Interior' WHERE name = 'Bagaj İçi';
UPDATE expertise_features SET name = 'Spare Tire' WHERE name = 'Stepne';
UPDATE expertise_features SET name = 'Engine Power' WHERE name = 'Motor gücü';
UPDATE expertise_features SET name = 'Horsepower' WHERE name = 'Beygir gücü';
UPDATE expertise_features SET name = 'Performance' WHERE name = 'Performans';
UPDATE expertise_features SET name = 'Left Front Fender' WHERE name = 'Sol Ön Çamurluk';
UPDATE expertise_features SET name = 'Left Front Door' WHERE name = 'Sol Ön Kapı';
UPDATE expertise_features SET name = 'Left Rear Fender' WHERE name = 'Sol Arka Çamurluk';
UPDATE expertise_features SET name = 'Front Bumper' WHERE name = 'Ön Tampon';
UPDATE expertise_features SET name = 'Hood' WHERE name = 'Kaput';
UPDATE expertise_features SET name = 'Roof' WHERE name = 'Tavan';
UPDATE expertise_features SET name = 'Trunk Lid' WHERE name = 'Bagaj Kapağı';
UPDATE expertise_features SET name = 'Rear Bumper' WHERE name = 'Arka Tampon';
UPDATE expertise_features SET name = 'Right Front Fender' WHERE name = 'Sağ Ön Çamurluk';
UPDATE expertise_features SET name = 'Right Front Door' WHERE name = 'Sağ Ön Kapı';
UPDATE expertise_features SET name = 'Right Rear Door' WHERE name = 'Sağ Arka Kapı';
UPDATE expertise_features SET name = 'Right Rear Fender' WHERE name = 'Sağ Arka Çamurluk';
UPDATE expertise_features SET name = 'Left Rear Door' WHERE name = 'Sol Arka Kapı';
UPDATE expertise_features SET name = 'Left Front Chassis' WHERE name = 'Sol Ön Şase';
UPDATE expertise_features SET name = 'Left Inner Wheel Arch' WHERE name = 'Sol İç Podye';
UPDATE expertise_features SET name = 'Left Inner Pillar' WHERE name = 'Sol İç Direk';
UPDATE expertise_features SET name = 'Left Upper Pillar' WHERE name = 'Sol Üst Direk';
UPDATE expertise_features SET name = 'Left Sill' WHERE name = 'Sol Marşpiyel';
UPDATE expertise_features SET name = 'Left Rear Chassis' WHERE name = 'Sol Arka Şase';
UPDATE expertise_features SET name = 'Front Panel' WHERE name = 'Ön Panel';
UPDATE expertise_features SET name = 'Front Windshield' WHERE name = 'Ön Cam';
UPDATE expertise_features SET name = 'Rear Window' WHERE name = 'Arka Cam';
UPDATE expertise_features SET name = 'Rear Panel' WHERE name = 'Arka Panel';
UPDATE expertise_features SET name = 'Rear Wheel Well Interior' WHERE name = 'Arka Havuz İçi';
UPDATE expertise_features SET name = 'Right Front Chassis' WHERE name = 'Sağ Ön Şase';
UPDATE expertise_features SET name = 'Right Inner Wheel Arch' WHERE name = 'Sağ İç Podye';
UPDATE expertise_features SET name = 'Right Inner Pillar' WHERE name = 'Sağ İç Direk';
UPDATE expertise_features SET name = 'Right Upper Pillar' WHERE name = 'Sağ Üst Direk';
UPDATE expertise_features SET name = 'Right Sill' WHERE name = 'Sağ Marşpiyel';
UPDATE expertise_features SET name = 'Right Rear Chassis' WHERE name = 'Sağ Arka Şase';
UPDATE expertise_features SET name = 'Engine Protective Cover' WHERE name = 'Motor Koruyucu Kapağı';
UPDATE expertise_features SET name = 'Air Filter Housing' WHERE name = 'Hava Filtre Kabini';
UPDATE expertise_features SET name = 'Engine Electrical System' WHERE name = 'Motor Elektrik Tesisatı';
UPDATE expertise_features SET name = 'Engine Oil & Sealing' WHERE name = 'Motor Yağı ve Sızdırmazlık';
UPDATE expertise_features SET name = 'Engine Oil Level' WHERE name = 'Motor Yağ Seviyesi';
UPDATE expertise_features SET name = 'Oil Cooler' WHERE name = 'Yağ Soğutucusu';
UPDATE expertise_features SET name = 'Engine Heat & Sound Insulation' WHERE name = 'Motor Isı ve Ses İzolasyon';
UPDATE expertise_features SET name = 'Turbo Intercooler Check' WHERE name = 'Turbo İntercooler Kontrolü';
UPDATE expertise_features SET name = 'EGR Valve & Injector Check' WHERE name = 'Egr Valfi ve Enjektör Kontrolü';
UPDATE expertise_features SET name = 'All Visible Belts' WHERE name = 'Görünen Tüm Kayışlar';
UPDATE expertise_features SET name = 'Engine Water Tightness' WHERE name = 'Motor Su Sızdırmazlık';
UPDATE expertise_features SET name = 'Fuel System & Sealing' WHERE name = 'Yakıt Sistemi ve Sızdırmazlık';
UPDATE expertise_features SET name = 'Steering Pump Check' WHERE name = 'Direksiyon Pompa Kontrolü';
UPDATE expertise_features SET name = 'Cooling Fans' WHERE name = 'Soğutma Fanları';
UPDATE expertise_features SET name = 'Engine Radiator & Core' WHERE name = 'Motor Su Radyatörü ve Paneli';
UPDATE expertise_features SET name = 'A/C Radiator & Pipes' WHERE name = 'Klima Radyatörü ve Boruları';
UPDATE expertise_features SET name = 'Engine Blow-by' WHERE name = 'Motor Üfleme';
UPDATE expertise_features SET name = 'Brake Fluid' WHERE name = 'Fren Hidroliği';
UPDATE expertise_features SET name = 'Engine Knocking/Irregular Operation' WHERE name = 'Motor Vuruntulu/Düzensiz Çalışma';
UPDATE expertise_features SET name = 'Turbo General Inspection' WHERE name = 'Turbo Genel Kontrolü';
UPDATE expertise_features SET name = 'Battery' WHERE name = 'Akü';
UPDATE expertise_features SET name = 'Front Left' WHERE name = 'Sol Ön';
UPDATE expertise_features SET name = 'Rear Left' WHERE name = 'Sol Arka';
UPDATE expertise_features SET name = 'Front Left' WHERE name = 'SOL ÖN';
UPDATE expertise_features SET name = 'Front Right' WHERE name = 'SAĞ ÖN';
UPDATE expertise_features SET name = 'Rear Left' WHERE name = 'SOL ARKA';
UPDATE expertise_features SET name = 'Rear Right' WHERE name = 'SAĞ ARKA';
UPDATE expertise_features SET name = 'Front Left Brake' WHERE name = 'ÖN SOL FREN';
UPDATE expertise_features SET name = 'Front Right Brake' WHERE name = 'ÖN SAĞ FREN';
UPDATE expertise_features SET name = 'Rear Left Brake' WHERE name = 'ARKA SOL FREN';
UPDATE expertise_features SET name = 'Rear Right Brake' WHERE name = 'ARKA SAĞ FREN';
UPDATE expertise_features SET name = 'Parking Brake Left' WHERE name = 'EL FRENI SOL';
UPDATE expertise_features SET name = 'Parking Brake Right' WHERE name = 'EL FRENI SAĞ';
UPDATE expertise_features SET name = 'Airbag Electronics' WHERE name = 'Hava Yastığı Elektroniğinde';
UPDATE expertise_features SET name = 'Engine Warning Light' WHERE name = 'Motor Arıza Lambası';
UPDATE expertise_features SET name = 'ABS/ESP/ESR Electronics' WHERE name = 'ABS / ESP / ESR Elektroniği';
UPDATE expertise_features SET name = 'A/C Electronics' WHERE name = 'Klima Elektroniği';
UPDATE expertise_features SET name = 'Tire Pressure Electronics' WHERE name = 'Lastik Basınç Elektroniği';
UPDATE expertise_features SET name = 'Electric Steering' WHERE name = 'Elektirikli Direksiyon';
UPDATE expertise_features SET name = 'Engine Control Unit Electronics' WHERE name = 'Motor Beyin Elektroniği';
UPDATE expertise_features SET name = 'Transmission Electronics' WHERE name = 'Şanzıman Elektroniği';
UPDATE expertise_features SET name = 'Spring & Shock Absorber (Front Right)' WHERE name = 'Yay ve Amörtisör (Sağ Ön)';
UPDATE expertise_features SET name = 'Spring & Shock Absorber (Front Left)' WHERE name = 'Yay ve Amörtisör (Sol Ön)';
UPDATE expertise_features SET name = 'Spring & Shock Absorber (Rear Right)' WHERE name = 'Yay ve Amörtisör (Sağ Arka)';
UPDATE expertise_features SET name = 'Spring & Shock Absorber (Rear Left)' WHERE name = 'Yay ve Amörtisör (Sol Arka)';
UPDATE expertise_features SET name = 'Brake Disc Condition (Front Right)' WHERE name = 'Fren Disk Durumu (Sağ Ön)';
UPDATE expertise_features SET name = 'Brake Disc Condition (Front Left)' WHERE name = 'Fren Disk Durumu (Sol Ön)';
UPDATE expertise_features SET name = 'Brake Disc Condition (Rear Right)' WHERE name = 'Fren Disk Durumu (Sağ Arka)';
UPDATE expertise_features SET name = 'Brake Disc Condition (Rear Left)' WHERE name = 'Fren Disk Durumu (Sol Arka)';
UPDATE expertise_features SET name = 'Brake Pad (Front Right)' WHERE name = 'Fren Balatası (Sağ Ön)';
UPDATE expertise_features SET name = 'Brake Pad (Front Left)' WHERE name = 'Fren Balatası (Sol Ön)';
UPDATE expertise_features SET name = 'Brake Pad (Rear Right)' WHERE name = 'Fren Balatası (Sağ Arka)';
UPDATE expertise_features SET name = 'Brake Pad (Rear Left)' WHERE name = 'Fren Balatası (Sol Arka)';
UPDATE expertise_features SET name = 'Tie Rods & Ball Joints' WHERE name = 'Rot Kolları ve Rot Başları';
UPDATE expertise_features SET name = 'Control Arm Bushing & Link Rods' WHERE name = 'Salıncak Burç Rotilleri';
UPDATE expertise_features SET name = 'Axle & Axle Boots' WHERE name = 'Aks ve Aks Körükleri';
UPDATE expertise_features SET name = 'Wheel & Tire (Front Right)' WHERE name = 'Jant ve Lastik (Sağ Ön)';
UPDATE expertise_features SET name = 'Wheel & Tire (Front Left)' WHERE name = 'Jant ve Lastik (Sol Ön)';
UPDATE expertise_features SET name = 'Wheel & Tire (Rear Right)' WHERE name = 'Jant ve Lastik (Sağ Arka)';
UPDATE expertise_features SET name = 'Wheel & Tire (Rear Left)' WHERE name = 'Jant ve Lastik (Sol Arka)';
UPDATE expertise_features SET name = 'Underbody Shield Check' WHERE name = 'Davlumbazların Kontrolü';
UPDATE expertise_features SET name = 'Engine & Transmission Mounts' WHERE name = 'Motor ve Şanzıman Alt Takozlar';
UPDATE expertise_features SET name = 'Engine Oil Sealing' WHERE name = 'Motor Yağ Sızdırmazlık';
UPDATE expertise_features SET name = 'Transmission Oil Sealing' WHERE name = 'Şanzıman Yağ Sızdırmazlık';
UPDATE expertise_features SET name = 'Differential Oil Sealing' WHERE name = 'Diferansiyel Yağ Sızdırmazlık';
UPDATE expertise_features SET name = 'Steering Gearbox Oil Sealing' WHERE name = 'Direksiyon Kutusu Yağ Sızdırmazlık';
UPDATE expertise_features SET name = 'A/C Compressor Oil Sealing' WHERE name = 'Klima Kompresörü Yağ Sızdırmazlık';
UPDATE expertise_features SET name = 'Clutch Check' WHERE name = 'Debriyaj Kontrol';
UPDATE expertise_features SET name = 'Exhaust Area Black Smoke' WHERE name = 'Egzoz Bölge Siyah Duman';
UPDATE expertise_features SET name = 'Exhaust Area Blue Smoke' WHERE name = 'Egzoz Bölge Mavi Duman';
UPDATE expertise_features SET name = 'Catalytic Converter System' WHERE name = 'Katalizör Sistemi';
UPDATE expertise_features SET name = 'Electric Power Steering' WHERE name = 'Elektrikli Direksiyon';
