"""initial schema

Revision ID: 9514469d6deb
Revises: 
Create Date: 2025-07-22 15:05:21.527707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9514469d6deb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street_address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expertise_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['expertise_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_expertise_types_parent_id'), 'expertise_types', ['parent_id'], unique=False)
    op.create_table('package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate', sa.String(length=10), nullable=False),
    sa.Column('engine_number', sa.String(length=17), nullable=True),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('chassis_number', sa.String(length=17), nullable=False),
    sa.Column('color', sa.Enum('BEIGE', 'WHITE', 'BURGUNDY', 'SMOKE', 'GRAY', 'SILVER_GRAY', 'BROWN', 'RED', 'NAVY_BLUE', 'BLUE', 'PURPLE', 'PINK', 'YELLOW', 'BLACK', 'CHAMPAGNE', 'TURQUOISE', 'ORANGE', 'GREEN', name='color'), nullable=False),
    sa.Column('model_year', sa.Integer(), nullable=False),
    sa.Column('transmission_type', sa.Enum('MANUAL', 'AUTOMATIC', 'SEMI_AUTOMATIC', name='transmissiontype'), nullable=False),
    sa.Column('fuel_type', sa.Enum('GASOLINE', 'LPG', 'DIESEL', 'ELECTRIC', 'HYBRID', name='fueltype'), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chassis_number'),
    sa.UniqueConstraint('engine_number'),
    sa.UniqueConstraint('plate')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('fax', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=100), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('tc_tax_number', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('package_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('content_item', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_id', 'content_item', name='uq_package_content_item')
    )
    op.create_table('package_expertises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('expertise_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['expertise_type_id'], ['expertise_types.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_expertises_expertise_type_id'), 'package_expertises', ['expertise_type_id'], unique=False)
    op.create_index(op.f('ix_package_expertises_package_id'), 'package_expertises', ['package_id'], unique=False)
    op.create_table('vehicle_owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('tc_tax_number', sa.String(length=11), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_owner_address_id'), 'vehicle_owner', ['address_id'], unique=False)
    op.create_index(op.f('ix_vehicle_owner_phone_number'), 'vehicle_owner', ['phone_number'], unique=False)
    op.create_index(op.f('ix_vehicle_owner_tc_tax_number'), 'vehicle_owner', ['tc_tax_number'], unique=False)
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_customer_id'), 'appointment', ['customer_id'], unique=False)
    op.create_table('branch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branch_address_id'), 'branch', ['address_id'], unique=False)
    op.create_index(op.f('ix_branch_company_id'), 'branch', ['company_id'], unique=False)
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_branch_id'), 'staff', ['branch_id'], unique=False)
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_date', sa.DateTime(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('registration_document_seen', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('OPENED', 'COMPLETED', 'CANCELLED', name='reportstatus'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_created_by'), 'report', ['created_by'], unique=False)
    op.create_index(op.f('ix_report_customer_id'), 'report', ['customer_id'], unique=False)
    op.create_index(op.f('ix_report_package_id'), 'report', ['package_id'], unique=False)
    op.create_index(op.f('ix_report_vehicle_id'), 'report', ['vehicle_id'], unique=False)
    op.create_table('agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expertise_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('expertise_type_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['expertise_type_id'], ['expertise_types.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expertise_reports_expertise_type_id'), 'expertise_reports', ['expertise_type_id'], unique=False)
    op.create_index(op.f('ix_expertise_reports_report_id'), 'expertise_reports', ['report_id'], unique=False)
    op.create_table('expertise_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('expertise_report_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['expertise_report_id'], ['expertise_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expertise_features_expertise_report_id'), 'expertise_features', ['expertise_report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expertise_features_expertise_report_id'), table_name='expertise_features')
    op.drop_table('expertise_features')
    op.drop_index(op.f('ix_expertise_reports_report_id'), table_name='expertise_reports')
    op.drop_index(op.f('ix_expertise_reports_expertise_type_id'), table_name='expertise_reports')
    op.drop_table('expertise_reports')
    op.drop_table('agent')
    op.drop_index(op.f('ix_report_vehicle_id'), table_name='report')
    op.drop_index(op.f('ix_report_package_id'), table_name='report')
    op.drop_index(op.f('ix_report_customer_id'), table_name='report')
    op.drop_index(op.f('ix_report_created_by'), table_name='report')
    op.drop_table('report')
    op.drop_index(op.f('ix_staff_branch_id'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_branch_company_id'), table_name='branch')
    op.drop_index(op.f('ix_branch_address_id'), table_name='branch')
    op.drop_table('branch')
    op.drop_index(op.f('ix_appointment_customer_id'), table_name='appointment')
    op.drop_table('appointment')
    op.drop_index(op.f('ix_vehicle_owner_tc_tax_number'), table_name='vehicle_owner')
    op.drop_index(op.f('ix_vehicle_owner_phone_number'), table_name='vehicle_owner')
    op.drop_index(op.f('ix_vehicle_owner_address_id'), table_name='vehicle_owner')
    op.drop_table('vehicle_owner')
    op.drop_index(op.f('ix_package_expertises_package_id'), table_name='package_expertises')
    op.drop_index(op.f('ix_package_expertises_expertise_type_id'), table_name='package_expertises')
    op.drop_table('package_expertises')
    op.drop_table('package_content')
    op.drop_table('customer')
    op.drop_table('company')
    op.drop_table('vehicle')
    op.drop_table('package')
    op.drop_index(op.f('ix_expertise_types_parent_id'), table_name='expertise_types')
    op.drop_table('expertise_types')
    op.drop_table('address')
    # ### end Alembic commands ###
