from .all_models import (
    Address,
    Agent,
    Appointment,
    Branch,
    Company,
    Customer,
    Package,
    PackageContent,
    PackageExpertise,
    ExpertiseType,
    ExpertiseReport,
    ExpertiseFeature,
    Report,
    Staff,
    Vehicle,
    VehicleOwner,
)